#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from __future__ import print_function

import argparse
import locale
import signal
import sys

import lib

b''  # Python >= 2.6 is required
if (3,) < sys.version_info < (3, 2):
    raise RuntimeError('Python >= 3.2 is required')

def process_file(options, path):
    stdout = sys.stdout
    if str is not bytes:
        stdout = stdout.buffer
    for s in lib.extract_strings(path):
        if isinstance(s, bytes):
            b = s
        else:
            b = s.encode(options.encoding, 'replace')
        stdout.write(b)
        stdout.write(b'\n')

def main():
    ap = argparse.ArgumentParser()
    default_encoding = sys.stdout.encoding or locale.getpreferredencoding()
    ap.add_argument('-e', '--encoding', default=default_encoding)
    ap.add_argument('--traceback', action='store_true', help=argparse.SUPPRESS)
    ap.add_argument('paths', metavar='PATH', nargs='+')
    options = ap.parse_args()
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    rc = 0
    for path in options.paths:
        try:
            process_file(options, path)
        except SyntaxError as exc:
            if options.traceback:
                raise
            msg = '{prog}: {path}: {exc}'.format(prog=ap.prog, path=path, exc=exc)
            print(msg, file=sys.stderr)
            rc = 1
    sys.exit(rc)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
