name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '2.7'
          os: ubuntu-20.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      if: matrix.python != '2.7'
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: set up Python 2.7 (with APT + get-pip)
      if: matrix.python == '2.7'
      run: |
        sudo apt-get install python-is-python2
        wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
        sudo python get-pip.py
        rm get-pip.py
    - name: run tests
      run: |
        prove -v
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: check README syntax
      run: |
        python -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
